name: Pipeline CI/CD

on:
  push:
   branches: 
    - main

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: build_ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject version into HTML
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Versão injetada: $VERSION"
          sed -i "s/{{VERSION}}/$VERSION/g" website/index.html       

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with: 
          role-to-assume: arn:aws:iam::890871562295:role/GithubActionsRepoApp 
          aws-region: us-east-2

      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build, Tag, and push image to Amazon ECR
        run: |
          docker build -t guinho-lab:v1.0 .
          docker tag guinho-lab:v1.0 890871562295.dkr.ecr.us-east-2.amazonaws.com/projeto-guinho:v1.0
          docker push 890871562295.dkr.ecr.us-east-2.amazonaws.com/projeto-guinho:v1.0

  job2:
    name: deploy_ec2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with: 
          role-to-assume: arn:aws:iam::890871562295:role/GithubActionsRepoApp
          aws-region: us-east-2

      - name: Deploy EC2 SSH
        run: |
          aws ssm send-command \
          --instance-ids "${EC2_INSTANCE_ID}" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy via GitHubActions" \
          --parameters  commands='[
            "aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 890871562295.dkr.ecr.us-east-2.amazonaws.com",
            "docker pull 890871562295.dkr.ecr.us-east-2.amazonaws.com/projeto-guinho:v1.0",
            "echo \"parando container antigo site \"",
            "docker stop site || true",
            "echo \"removendo container antigo site\"",
            "docker rm site || true",
            "echo \"rodando nova tag da imagem\"",
            "docker run -d -p 80:80 --name site 890871562295.dkr.ecr.us-east-2.amazonaws.com/projeto-guinho:v1.0",
            "echo \"Parabéns! Imagem foi atualizada!\"",
            "docker ps"
          ]'
          
